version: '2'
services:
  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test12
    ports:
      - 3306:3306
    networks:
      - employee-app
    volumes:
      - mysql_data:/mysql

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    networks:
      - employee-app

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - employee-app

  employee_modifications:
    image: andreiazemsha/employee_modifications:latest
    container_name: employee_modifications
    expose:
      - 8095
    ports:
      - 8095:8095
    volumes:
      - /var/tmp
    restart: unless-stopped
    environment:
      - DATABASE_HOST=mysql
      - DATABASE_USER=root
      - DATABASE_PASSWORD=test12
      - DATABASE_NAME=employee
      - DATABASE_PORT=3306
    networks:
      - employee-app
    depends_on:
      - mysql
      - kafka

networks:
  employee-app:
    driver: bridge

volumes:
  mysql_data:
    driver: local
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local